apiVersion: vault.ops.community.dev/v1alpha1
kind: AppRole
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: approle-sample
spec:
  # TODO(user): Add fields here
