apiVersion: vault.ops.community.dev/v1alpha1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: secret-sample
spec:
  name: my-secret
  vaultOperator:
    name: vaultserver-sample
  mountPath: daniel
  path: app1/creds
  data:
    username: daniel
    password: s3cr3t
    token: "{{random}}"

