apiVersion: vault.ops.community.dev/v1alpha1
kind: SecretEngine
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretengine-sample
spec:
  vaultOperator:
    name: vaultserver-sample
  type: kv-v2
  path: my-kv-secret-engine